name: findux_mobile
description: FindUX Mobile App
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.13.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/legal/
    - assets/data/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
